Product:
    type: object
    config:
        fields:
            name:
                type: "String!"
            description:
                type: "String"
            quantity:
                type: "Int!"
#            expireAt:
#                type: "Date"
#            type:
#                type: "ProductType!"
#            packaging:
#                type: "Packaging!"
#            storage:
#                type: "Storage!"
#            createdAt:
#                type: "Date!"
#            updatedAt:
#                type: "Date"
